---
- hosts: all
  become: true
  vars:
      home: /home/vagrant
      document_root: /vagrant
      os: ubuntu
      user: vagrant
      osversioncode: xenial
  gather_facts: no
  pre_tasks:
      - name: Install sudo
        apt: name=sudo state=installed
      - name: Symlink sh to bash rather than dash
        file: src=/bin/bash dest=/bin/sh state=link force=true
      - name: Update apt cache and optionally upgrade
        apt:
          update_cache=yes
          cache_valid_time=7200
          #upgrade=yes # Uncomment this to force full upgrade!
      - name: Install stuff from Aptitude
        apt: name={{ item }} state=installed
        with_items:
         - bash-completion # Not included in the docker image
         - cgdb
         - gdb
         - git
         - htop
         - make
         - man-db
         - python-simplejson
         - tig
         - tmux
         - tree
         - vim
  roles:
      - { role: dotfiles, become: false }
      - { role: golang, become: false }
      #- { role: youcompleteme, sudo: false } # Comment out this to save time!!
      #- { role: mesos, sudo: false }
